WITH `bfcte_0` AS (
  SELECT
    *
  FROM UNNEST(ARRAY<STRUCT<`bfcol_0` BOOLEAN, `bfcol_1` BYTES, `bfcol_2` DATE, `bfcol_3` DATETIME, `bfcol_4` GEOGRAPHY, `bfcol_5` INT64, `bfcol_6` INT64, `bfcol_7` NUMERIC, `bfcol_8` FLOAT64, `bfcol_9` INT64, `bfcol_10` INT64, `bfcol_11` STRING, `bfcol_12` TIME, `bfcol_13` TIMESTAMP, `bfcol_14` INT64>>[STRUCT(
    CAST(NULL AS BOOLEAN),
    CAST(NULL AS BYTES),
    CAST(NULL AS DATE),
    CAST(NULL AS DATETIME),
    CAST(NULL AS GEOGRAPHY),
    CAST(NULL AS INT64),
    CAST(NULL AS INT64),
    CAST(NULL AS NUMERIC),
    CAST(NULL AS FLOAT64),
    CAST(NULL AS INT64),
    CAST(NULL AS INT64),
    CAST(NULL AS STRING),
    CAST(NULL AS TIME),
    CAST(NULL AS TIMESTAMP),
    CAST(NULL AS INT64)
  )])
), `bfcte_1` AS (
  SELECT
    COUNT(1) AS `bfcol_32`
  FROM `bfcte_0`
)
SELECT
  `bfcol_32` AS `size`
FROM `bfcte_1`